### ISSUE TITLE
Multiple issues discovered with Shellcheck

### ISSUE THREAD

**Issue by ikstream** [Jarl-Bjoern/Yggdrasil#1]
Thank you for the useful tool.

I checked the `configurator.sh` script file with shellcheck. After removing the carriage return (`\r`) it produce quite some output. 
While most of it was about double quoting to avoid globbing there were some findings like missing white spaces, that might cause actual issues.
An example can be seen in [line 856](https://github.com/Jarl-Bjoern/Yggdrasil/blob/9b1b0266686d58f9ee8492f63e5c89d654b7382a/configurator.sh#L856). In additions there are other Warnings which might improve the good code quality further.

It might be useful to run shellcheck against the configuration script.

If you need or want assistance in this task let me know.

BR
ikstream

**Comment by Jarl-Bjoern** [comment]
Thanks for the feedback.

Almost all errors from the shellcheck output have been fixed and the program should be ready to use now.

The lines (9 and 246) will be fixed in the next days and the two remaining switches will be used in the near future. 

The issue with the white spaces will also be fixed as soon as possible.

Best Regards

Jarl-Björn

**Comment by Jarl-Bjoern** [comment]
All problems have been fixed.

The problem with spaces is currently fixed by using the dos2unix tool, which also starts after launching yggdrasil and converts all files to the correct format.

Best regards

Jarl-Björn

**Comment by Jarl-Bjoern** [comment]
A small update to the problem from last time.

The `dos2unix` tool was replaced by a self-written converter to remove all `\r`.

Best regards

Jarl-Björn
