### ISSUE TITLE
Tool install not working

### ISSUE THREAD

**Issue by snuxs** [Jarl-Bjoern/Yggdrasil#2]
Hey there, thanks for the tool, it is really helpful!

Since version 0.9b I cannot install anything. It is possible for me to configure the hardening part, IP and config.
All other options (Pentest/Foresnic tools) do not show. 

I started the tool like so:
`sudo python3 yggdrasil.py -aL`

Also tried skipping hardening and config. Skips the parts but it is not possible to choose the tool installation.
`sudo python3 yggdrasil.py -aL -sC -sH`

Output is:

```
grep: : No such file or directory
Installation successful
```

Thought it was a configuration error on my side, so downloaded version 0.9 on the same machine and everythign worked as expected.

Thank you for your help and your tool!

BR 
snuxs

**Comment by Jarl-Bjoern** [comment]
Hey snuxs.

Thanks for your message and the positive feedback.

The problem was found and fixed immediately and was due to a programming error on my side. It should be related to the new (today) adapted feature `Skip_Installation, -sI`, which is `only` available on `version 0.9c`. The above error `should not` normally occur in `version 0.9b`.

Did you download the tool via `git clone` from the main page or specifically the `stable release 0.9b` from the [releases](https://github.com/Jarl-Bjoern/Yggdrasil/releases/tag/V0.9b) page? The first variant is practically the `beta or pre version` of the tool for the upcoming release (`version 0.9c`). Unfortunately, this can also result in errors, because the newly added functions cannot fully tested at this time. I will be updating the documentation as soon as possible to clear up the confusion with the version numbers.

I hope that the problem has been solved and please do not hesitate to contact me if there are any further problems. :)

BR

JarlBjoern

**Comment by snuxs** [comment]
Hey,

I tried and it works perfectly fine again, thanks for the fix!
(I used `git clone` again for testing purposes.)

Yes, you are right, I used `git clone` from the main page. Did not consider that I could have downloaded a beta.

BR 
snuxs
